name: Core
version: '${version}'
main: com.tricrotism.core.Core
api-version: '1.20'
commands:
  dev/actionbar:
    description: "Send an action bar message to a player"
  dev/bossbar:
    description: "Send a boss bar message to a player"
  givetreecapitator:
    description: "Gives a player the TreeCapitator item"
  givethorsaxe:
    description: "Gives a player the Thor's Axe item"
  teleport:
    description: "Teleport to a player or location"
    aliases: [ tp, tpo ]
  tpa:
    description: "Request to teleport to a player"
    aliases: [ tpask, tpaccept, tpdeny ]
  tpaccept:
    description: "Accept a teleport request"
  tpdeny:
    description: "Deny a teleport request"